name: Bandit Security Report

on:
  push:

jobs:
  generate-report:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Run Bandit Action
      uses: shundor/bandit-action@v1
      with:
        path: "."
        exit_zero: true
