name: Bandit Security Report

on:
  push:
  workflow_dispatch:

jobs:
  generate-report:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Run Bandit Action
      uses: shundor/python-bandit-scan@v1.0
      with:
        # path: "."
        # exit_zero: true
