name: playground

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag or branch'
        required: true
  push:
    tags:
      - "*"

jobs:
  get-tag:
    # if: ${{ github.event.base_ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Tag Name example
        run: |
          echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME:"
          echo "Tag name from github.ref_name: ${{  github.ref_name }}"
          echo "github.ref: ${{ github.ref }}"
          echo "github.event.inputs.release_tag: ${{ github.event.inputs.release_tag }}"
          echo "github.event.base_ref: ${{ github.event.base_ref }}"
